const mongoose = require('mongoose');

// Define the structure of the TravelGuide document
const travelGuideSchema = new mongoose.Schema({
    // Link the guide to a specific user
    user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    destination: { type: String, required: true },
    budget: { type: Number, required: true },
    numberOfPeople: { type: Number, required: true },
    days: { type: Number, required: true },
    // This will store the rich text or markdown generated by the AI
    guideContent: { type: String, required: true },
    createdAt: { type: Date, default: Date.now },
});

// Create and export the TravelGuide model
module.exports = mongoose.model('TravelGuide', travelGuideSchema);